### ISSUE TITLE
Just out of curiosity

### ISSUE THREAD

**Issue by tigt** [tumblr/laphs#5]
Why

``` html
<img src="STILL-PHOTO.jpg" data-live-photo="LIVE-PHOTO.mov" data-live-photo-still-image-time="1.71"/>
```

and not

``` html
<video poster="STILL-PHOTO.jpg" src="LIVE-PHOTO.mov"></video>
```

? I feel like there's a really good compatibility reason, I'm just curious to know what it is.

**Comment by heylookltsme** [comment]
That's a good question @tigt! Under the hood, laphs is actually producing two `<video>` elements in order to achieve the unique playback exactly to spec.  Plus, at least to my mind, philosophically a live photo is primarily a photo with a video attached to it, rather than the other way around. /shrug 

Thanks for your interest!

**Comment by heylookltsme** [comment]
Gonna close this to keep the issues tidy, but feel free to keep the convo going if you like.
